### ISSUE TITLE
interesting

### ISSUE THREAD

**Issue by dcsan** [mariohmol/rivescript-viz#1]
just so i understand - this is a client side visualisation of a Rive file, using D3?
(and a bit of angular too)

did you know there's a way to actually extract the nodes from Rive brain itself? `deparse` method.
that maybe better than using the regex
https://github.com/mariohmol/rivescript-viz/blob/master/public/rivescript-viz.js#L23

great start!

**Comment by mariohmol** [comment]
well.. this is node/express that open all .rive files in backend using Riverbot and send to frontend in angular/d3
 
Here i get the topic list:
* https://github.com/mariohmol/rivescript-viz/blob/master/server.js#L23

But the thing is, when I access the trigger.reply it has something like `^ <set retry=0>{topic=interview2}`

So, using deparse i have this set, topic and other variables as a object?

**Comment by mariohmol** [comment]
updated readme with projec specs
